### PR TITLE
Fix computation of app path when published as a "single file"

### LINKED ISSUE #229: WSL2 Ubuntu 18.04 - Unable to Perform Any Type of Setup
**Which version of GCM Core are you using?**

From a terminal, run `git-credential-manager-core version` and paste the output.

Git Credential Manager version 2.0.280-beta+1f4c6db90f (Linux, .NET Core 3.1.6)

**Which Git host provider are you trying to connect to?**

* [ ] Azure DevOps
* [ ] Azure DevOps Server (TFS/on-prem)
* [x] GitHub
* [ ] GitHub Enterprise
* [ ] Bitbucket
* [ ] Other - please describe

**Can you access the remote repository directly in the browser using the remote URL?**

From a terminal, run `git remote -v` to see your remote URL.

* [x] Yes
* [ ] No, I get a permission error
* [ ] No, for a different reason - please describe

---

**_[Azure DevOps only]_ What format is your remote URL?**

* [ ] Not applicable
* [ ] https://dev.azure.com/`{org}`/...
* [ ] https://`{org}`@dev.azure.com/`{org}`/...
* [ ] https://`{org}`.visualstudio.com/...

**_[Azure DevOps only]_ If the account picker shows more than one identity as you authenticate, check that you selected the same one that has access on the web.**

* [ ] Not applicable
* [ ] I only see one identity
* [ ] I checked each identity and none worked

---

**Expected behavior**

I am authenticated and my Git operation completes successfully.

**Actual behavior**

Following the setup steps for Linux in WSL2 Ubuntu 18.04, I cannot even get the plaintext store to work. I see the following when trying to clone a private repo from github.com. Inputting a PAT does not store the token and `~/.gcm/store` is not created. I've had similar issues with the gpg/pass setup. (Tried avoiding gpg for the moment just to see if I could get the simpler plaintext setup in place -- I think something else is going on, though.) I did the setup via the .deb package.

image

**Logs**

Set the environment variables `GCM_TRACE=1` and `GIT_TRACE=1` and re-run your Git command. Review and redact any private information and attach the log.

Log is attached.

[git.log](https://github.com/microsoft/Git-Credential-Manager-Core/files/5580017/git.log)

### LINKED ISSUE #252: git-credential-manager-core: not found
Hi,

After attempting to install from `.deb` out of the box on linux, I hit this issue:

```
/var/tmp/.net/nipunn/git-credential-manager-core/sgmxzdfz.svu/git-credential-manager-core get: 1: /var/tmp/.net/nipunn/git-credential-manager-core/sgmxzdfz.svu/git-credential-manager-core get: /var/tmp/.net/nipunn/git-credential-manager-core/sgmxzdfz.svu/git-credential-manager-core: not found
```

I followed the instructions by first installing the dpkg - then running

```
git-credential-manager-core configure
git config --global credential.credentialStore gpg  # same issue regardless of what I select here
```

Other potentially helpful information
```
nipunn@nipunn-desk:~$ git-credential-manager-core --version
Git Credential Manager version 2.0.289-beta+22bd06dc57 (Linux, .NET Core 3.1.10)
nipunn@nipunn-desk:~$ which git-credential-manager-core
/usr/bin/git-credential-manager-core
```

If I manually edit ~/.gitconfig to search for the path `/usr/bin/git-credential-manager-core` instead of the one in /var/tmp, then things work. I suspect this might be an issue with `git-credential-manager-core --configure` Not sure where this /var/tmp is coming from.

I noticed the directory where it searches for git-credential-manager-core is filled with dll's
```
nipunn@nipunn-desk:~$ ls /var/tmp/.net/nipunn/git-credential-manager-core/sgmxzdfz.svu
Atlassian.Bitbucket.dll
createdump
git-credential-manager-core.deps.json
git-credential-manager-core.dll
git-credential-manager-core.runtimeconfig.json
GitHub.dll
libclrjit.so
libcoreclr.so
libcoreclrtraceptprovider.so
libdbgshim.so
libhostfxr.so
libhostpolicy.so
libmscordaccore.so
libmscordbi.so
Microsoft.AzureRepos.dll
Microsoft.CSharp.dll
Microsoft.Extensions.Configuration.Abstractions.dll
Microsoft.Extensions.Configuration.Binder.dll
Microsoft.Extensions.Configuration.dll
Microsoft.Extensions.Configuration.EnvironmentVariables.dll
Microsoft.Extensions.DependencyInjection.Abstractions.dll
Microsoft.Extensions.Logging.Abstractions.dll
Microsoft.Extensions.Logging.dll
Microsoft.Extensions.Options.dll
Microsoft.Extensions.Primitives.dll
Microsoft.Git.CredentialManager.dll
Microsoft.Identity.Client.dll
Microsoft.Identity.Client.Extensions.Msal.dll
Microsoft.IdentityModel.JsonWebTokens.dll
Microsoft.IdentityModel.Logging.dll
Microsoft.IdentityModel.Tokens.dll
Microsoft.VisualBasic.Core.dll
Microsoft.VisualBasic.dll
Microsoft.Win32.Primitives.dll
Microsoft.Win32.Registry.dll
mscorlib.dll
netstandard.dll
Newtonsoft.Json.dll
NOTICE
SOS_README.md
System.AppContext.dll
System.Buffers.dll
System.Collections.Concurrent.dll
System.Collections.dll
System.Collections.Immutable.dll
System.Collections.NonGeneric.dll
System.Collections.Specialized.dll
System.ComponentModel.Annotations.dll
System.ComponentModel.DataAnnotations.dll
System.ComponentModel.dll
System.ComponentModel.EventBasedAsync.dll
System.ComponentModel.Primitives.dll
System.ComponentModel.TypeConverter.dll
System.Configuration.dll
System.Console.dll
System.Core.dll
System.Data.Common.dll
System.Data.DataSetExtensions.dll
System.Data.dll
System.Diagnostics.Contracts.dll
System.Diagnostics.Debug.dll
System.Diagnostics.DiagnosticSource.dll
System.Diagnostics.FileVersionInfo.dll
System.Diagnostics.Process.dll
System.Diagnostics.StackTrace.dll
System.Diagnostics.TextWriterTraceListener.dll
System.Diagnostics.Tools.dll
System.Diagnostics.TraceSource.dll
System.Diagnostics.Tracing.dll
System.dll
System.Drawing.dll
System.Drawing.Primitives.dll
System.Dynamic.Runtime.dll
System.Globalization.Calendars.dll
System.Globalization.dll
System.Globalization.Extensions.dll
System.Globalization.Native.so
System.IO.Compression.Brotli.dll
System.IO.Compression.dll
System.IO.Compression.FileSystem.dll
System.IO.Compression.Native.a
System.IO.Compression.Native.so
System.IO.Compression.ZipFile.dll
System.IO.dll
System.IO.FileSystem.AccessControl.dll
System.IO.FileSystem.dll
System.IO.FileSystem.DriveInfo.dll
System.IO.FileSystem.Primitives.dll
System.IO.FileSystem.Watcher.dll
System.IO.IsolatedStorage.dll
System.IO.MemoryMappedFiles.dll
System.IO.Pipes.AccessControl.dll
System.IO.Pipes.dll
System.IO.UnmanagedMemoryStream.dll
System.Linq.dll
System.Linq.Expressions.dll
System.Linq.Parallel.dll
System.Linq.Queryable.dll
System.Memory.dll
System.Native.a
System.Native.so
System.Net.dll
System.Net.Http.dll
System.Net.HttpListener.dll
System.Net.Http.Native.a
System.Net.Http.Native.so
System.Net.Mail.dll
System.Net.NameResolution.dll
System.Net.NetworkInformation.dll
System.Net.Ping.dll
System.Net.Primitives.dll
System.Net.Requests.dll
System.Net.Security.dll
System.Net.Security.Native.a
System.Net.Security.Native.so
System.Net.ServicePoint.dll
System.Net.Sockets.dll
System.Net.WebClient.dll
System.Net.WebHeaderCollection.dll
System.Net.WebProxy.dll
System.Net.WebSockets.Client.dll
System.Net.WebSockets.dll
System.Numerics.dll
System.Numerics.Vectors.dll
System.ObjectModel.dll
System.Private.CoreLib.dll
System.Private.DataContractSerialization.dll
System.Private.Uri.dll
System.Private.Xml.dll
System.Private.Xml.Linq.dll
System.Reflection.DispatchProxy.dll
System.Reflection.dll
System.Reflection.Emit.dll
System.Reflection.Emit.ILGeneration.dll
System.Reflection.Emit.Lightweight.dll
System.Reflection.Extensions.dll
System.Reflection.Metadata.dll
System.Reflection.Primitives.dll
System.Reflection.TypeExtensions.dll
System.Resources.Reader.dll
System.Resources.ResourceManager.dll
System.Resources.Writer.dll
System.Runtime.CompilerServices.Unsafe.dll
System.Runtime.CompilerServices.VisualC.dll
System.Runtime.dll
System.Runtime.Extensions.dll
System.Runtime.Handles.dll
System.Runtime.InteropServices.dll
System.Runtime.InteropServices.RuntimeInformation.dll
System.Runtime.InteropServices.WindowsRuntime.dll
System.Runtime.Intrinsics.dll
System.Runtime.Loader.dll
System.Runtime.Numerics.dll
System.Runtime.Serialization.dll
System.Runtime.Serialization.Formatters.dll
System.Runtime.Serialization.Json.dll
System.Runtime.Serialization.Primitives.dll
System.Runtime.Serialization.Xml.dll
System.Runtime.WindowsRuntime.dll
System.Runtime.WindowsRuntime.UI.Xaml.dll
System.Security.AccessControl.dll
System.Security.Claims.dll
System.Security.Cryptography.Algorithms.dll
System.Security.Cryptography.Cng.dll
System.Security.Cryptography.Csp.dll
System.Security.Cryptography.Encoding.dll
System.Security.Cryptography.Native.OpenSsl.a
System.Security.Cryptography.Native.OpenSsl.so
System.Security.Cryptography.OpenSsl.dll
System.Security.Cryptography.Primitives.dll
System.Security.Cryptography.ProtectedData.dll
System.Security.Cryptography.X509Certificates.dll
System.Security.dll
System.Security.Principal.dll
System.Security.Principal.Windows.dll
System.Security.SecureString.dll
System.ServiceModel.Web.dll
System.ServiceProcess.dll
System.Text.Encoding.CodePages.dll
System.Text.Encoding.dll
System.Text.Encoding.Extensions.dll
System.Text.Encodings.Web.dll
System.Text.Json.dll
System.Text.RegularExpressions.dll
System.Threading.Channels.dll
System.Threading.dll
System.Threading.Overlapped.dll
System.Threading.Tasks.Dataflow.dll
System.Threading.Tasks.dll
System.Threading.Tasks.Extensions.dll
System.Threading.Tasks.Parallel.dll
System.Threading.Thread.dll
System.Threading.ThreadPool.dll
System.Threading.Timer.dll
System.Transactions.dll
System.Transactions.Local.dll
System.ValueTuple.dll
System.Web.dll
System.Web.HttpUtility.dll
System.Windows.dll
System.Xml.dll
System.Xml.Linq.dll
System.Xml.ReaderWriter.dll
System.Xml.Serialization.dll
System.Xml.XDocument.dll
System.Xml.XmlDocument.dll
System.Xml.XmlSerializer.dll
System.Xml.XPath.dll
System.Xml.XPath.XDocument.dll
WindowsBase.dll
```

### PR DESCRIPTION
**Pull request by mjcheetham**
When publishing GCM as a 'single file' application, the computed path to the entry executable is no longer correct.
    
On .NET Core 3.1, using `Assembly.Location` resolves to the temporary extracted DLL file path. On .NET 5 `Assembly.Location` always returns the empty string.
    
Since .NET 5, published single-file apps no longer use the self-extraction model, and are real single file with all assemblies and native libraries statically linked/bundled.

We now use the `Environment.GetCommandLineArgs()` method to get the raw underlying "argv" arguments, which argv[0] is the absolute file path to the entry executable.
    
We also change how we get the application version number to look for the assembly attribute, rather than extract if from the file on disk.
    
At app startup, also change the way we trace system information to be more readable.

Fixes #229
Fixes #252

### CODE REVIEW

File: src/shared/Git-Credential-Manager/Program.cs [hunk 1]
```diff
@@ -36,16 +37,19 @@ public static void Main(string[] args)
...
-                throw new InvalidOperationException();
-            }
+            // Assembly::Location always returns an empty string if the application was published as a single file
+#pragma warning disable IL3000
+            bool isSingleFile = string.IsNullOrEmpty(Assembly.GetEntryAssembly()?.Location);
+#pragma warning restore IL3000
 
-            string candidatePath = entryAssembly.Location;
+            // Use "argv[0]" to get the full path to the entry executable - this is consistent across
+            // .NET Framework and .NET >= 5 when published as a single file.
```
Comment (kyle-rader) [inline src/shared/Git-Credential-Manager/Program.cs:46]: 👍🏻

**Review by kyle-rader — APPROVED** [review]
Thanks!

**Review by jeffhostetler — APPROVED** [review]
